### ISSUE TITLE
mod_cfml Apache 2.4 VC16 build

### ISSUE THREAD

**Issue by zspitzer** [viviotech/mod_cfml#21]
The download for mod_cfml for Apache on Windows is a VC10 build
https://viviotech.github.io/mod_cfml/download.html

The last Windows Apache 2.4 VC10 build which is available is 2.4.23
https://www.apachelounge.com/download/VC10/

The latest version is Apache 2.4.39 Win64 which is only available for VC15 and VC14
https://www.apachelounge.com/download/

> Build with the latest Windows® Visual Studio C++ 2017 aka VC15. VC15 has improvements, fixes and optimizations over VC14 in areas like Performance, MemoryManagement, New standard conformance features, Code generation and Stability. For example code quality tuning and improvements done across different code generation areas for "speed". And makes more use of modern processors and supported Windows editions (win 7 and up) internal features.

**Comment by paulklinkenberg** [comment]
@utdream do you have a build server/vm for this? If not, I could give it a try.
Or did you already do a build, @zspitzer? In that case, please pass it along!

**Comment by zspitzer** [comment]
@paulklinkenberg I haven't done a build

**Comment by utdream** [comment]
@paulklinkenberg I do not. I would need to create a new VM for it and set up the VM to perform builds. If you've already got a build environment set up, please feel free! If you find you don't have time, I can do it too. Either way, thank you for your help!

**Comment by zspitzer** [comment]
here's a VS16 build of mod_cfml.so for Apache 2.4.41 x64 compiled for VS16 

[mod_cfml_Apache24_x64_VS16.zip](https://github.com/viviotech/mod_cfml/files/3657741/mod_cfml_Apache24_x64_VS16.zip)

I built it using VS 2019

As Apache 2.2 is EOL, I don't think it's needed and is anyone even using 32 bit anymore?

**Comment by zspitzer** [comment]
it was reported on slack that this isn't working, **silently not starts, error.log has nothing** 

I'll investigate this tonight

**Comment by rodionbykov** [comment]
In Windows Event Viewer: EventID 3299 Level 2
The Apache service reported the following error:
httpd.exe: Syntax error on line 186 of C:/Apache24/conf/httpd.conf: Cannot load  modules/mod_cfml.so into server: The specified module could not be found.

File mod_cfml.so is placed together with other modules into C:/Apache24/modules folder

**Comment by zspitzer** [comment]
what is ServerRoot set to?
https://httpd.apache.org/docs/2.4/mod/core.html#serverroot

**Comment by utdream** [comment]
@rodionbykov This may seem like a basic question, but have you checked the permissions on the .so file? Cannot be found is a pretty basic error message. If it was a compile error or something like that I would presume you'd get some kind of exception rather than a file not found error. Maybe Apache just can't see it?

**Comment by utdream** [comment]
@zspitzer I'm heading out of town for a couple weeks on business, so I won't be able to test this until I get back, but I will get to it as soon as I have time! Thank you for your help. =)

**Comment by rodionbykov** [comment]
That's what comes in httpd.conf by default, I did not changed it.

Define SRVROOT "C:/Apache24"
ServerRoot "${SRVROOT}" 

Permissions checked, they are same as for other modules, which apparently loading ok (proxy, ajp, rewrite)

**Comment by paulklinkenberg** [comment]
Hi there!
I was just reading through this topic, and have some tips, which might be useful:
- for the older apache-windows module, we have a (.net?) dependency which needs to be installed first. Could a missing dependency, but a different version, be the culprit in this situation?
- @Zac: can you confirm the module you zipped and sent, was tested on the same platform and apache version as the person currently having the issue with it?

Kind regards,

Paul Klinkenberg

------------



Op 26 sep. 2019 om 14:51 heeft Zac Spitzer <notifications@github.com> het volgende geschreven:

here's a VS16 build of mod_cfml.so for Apache 2.4.41 x64 compiled for VS16

mod_cfml_Apache24_x64_VS16.zip

I built it using VS 2019

As Apache 2.2 is EOL, I don't think it's needed and is anyone even using 32 bit anymore?

**Comment by zspitzer** [comment]
yeah, I'm on Win10 with the same version of Apache

here's the cmakesettings.json file from VS Studio I ended up with

[CMakeSettings.json.zip](https://github.com/viviotech/mod_cfml/files/3689738/CMakeSettings.json.zip)

**Comment by paulklinkenberg** [comment]
Hi Zac, thanks for the confirmation!

@Rodion: you could try to install the "Visual C++ red. Package” from the Microsoft site: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads <https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads>, to make the module work. It does make sense that would be the problem.

In this case (the module built with VS 2019), it would be one of:
x86: vc_redist.x86.exe <https://aka.ms/vs/16/release/vc_redist.x86.exe>
x64: vc_redist.x64.exe <https://aka.ms/vs/16/release/vc_redist.x64.exe>
ARM64: vc_redist.arm64.exe <https://aka.ms/vs/16/release/VC_redist.arm64.exe>
Could you try, and let us know if that solves it?

Thanks!

Kind regards,

Paul Klinkenberg

**Comment by rodionbykov** [comment]
Tried: 
- installed VC redistributable x64 and x86
- installed .net framework
- removed Apache, downloaded again, unzipped to C:/Apache24
https://www.apachelounge.com/download/VS16/binaries/httpd-2.4.41-win64-VS16.zip
- downloaded mod_cfml, unzipped to C:/Apache24/modules
https://github.com/viviotech/mod_cfml/files/3657741/mod_cfml_Apache24_x64_VS16.zip
- checked permissions and ownership of .so files
- in httpd.conf added
LoadModule modcfml_module modules/mod_cfml.so
CFMLHandlers ".cfm .cfc .cfml"
ModCFML_SharedKey "blabla"

Result: start apache failed, in Windows event viewer always same issue - modules/mod_cfml.so could not be found. 

For now, giving up :) Working with Apache+mod_cfml+Lucee in Windows Subsystem for Linux

**Comment by zspitzer** [comment]
This is becoming rather critical due to ghostcat, Apache 2.4.42 is coming out soon, which can't be used unless we get this working

https://github.com/viviotech/lucee-installer/issues/100

**Comment by paulklinkenberg** [comment]
I will give it a go. I don't have the previous build VMs lying around anymore, but I'll see what I can do.

**Comment by utdream** [comment]
Ugh. I feel bad. I remember now that I was going to look into this and totally spaced it. Sorry @paulklinkenberg , this one is on me. If you want help with anything, just say the word. Will assign this to you atm.

**Comment by paulklinkenberg** [comment]
> Ugh. I feel bad. I remember now that I was going to look into this and totally spaced it. Sorry @paulklinkenberg , this one is on me. If you want help with anything, just say the word. Will assign this to you atm.

It is actually quite nice to be taking a deep-dive into the code again ;-) shamefully, I have to follow the steps from my own tutorial now. It’s been too long 🙄
I have built the versions already. Just have to test them on some windows machines (who uses windows anyway?!)

**Comment by paulklinkenberg** [comment]
I created the VC16 builds, at:
* https://github.com/paulklinkenberg/mod_cfml/tree/VC14_VC16_builds/C/builds/windows-httpd24-x64-VC16
* https://github.com/paulklinkenberg/mod_cfml/tree/VC14_VC16_builds/C/builds/windows-httpd24-x86-VC16

Then, tested it on an x64 machine, Win server 2012 R2 datacenter edition.
It ran succesfully on the following Apache 2.4 versions (from apachelounge.com):
* httpd-2.4.41-win64-VS16
* httpd-2.4.41-win64-VC14
* httpd-2.4.41-win32-VC14 

@zspitzer @rodionbykov @utdream Would you please test and confirm the new builds are working on your environments? You can be launching customers :-D

**Comment by paulklinkenberg** [comment]
I also left a "call for testers" at the Lucee dev mailing list: https://dev.lucee.org/t/testers-needed-mod-cfml-windows-apache-component/6679

**Comment by zspitzer** [comment]
Working nicely for me on Win10 and Windows Server 2019 with x64 VC16 Apache 2.4.41

**Comment by paulklinkenberg** [comment]
Thanks for testing! The total turn-up for testing was 1 person in total, namely @zspitzer ;)
Anyway, because I do not expect any bugs with them (it either works or doesn't), I will do a PR now.

**Comment by rodionbykov** [comment]
Tested OK with latest Lucee 5.3.4.77 installer and httpd-2.4.41-win64-VS16 on Windows 10

**Comment by paulklinkenberg** [comment]
Thanks for testing @rodionbykov

**Comment by utdream** [comment]
Apologies for the delay. I carved out some time today to work on this and I don't have it working with the "secret" parameter specified. I am getting the "ProxyPass unknown Worker parameter" error which seems to indicate that my version of Apache 2.4.41/mod_proxy_ajp doesn't support the "secret" parameter. (https://www.mail-archive.com/users@httpd.apache.org/msg66168.html)

Works fine without the "secret=whatever" parameter. Did you guys test with a secret? Using the Apache Lounge Distribution - Apache 2.4.41 win64 VS16. That the same one you used? What am I missing?

**Comment by utdream** [comment]
@paulklinkenberg On a separate but related note, when I added the responseCode functionality to the mod_cfml valve I also bumped it's version to 1.1.11. Do you think it might be prudent to keep the Apache module the same version number as the Valve to avoid confusion as to what version of mod_cfml people are using? I realize they are different pieces within the project, but I think it might be confusing to keep different versions for each piece. Thoughts?

**Comment by utdream** [comment]
@paulklinkenberg Ref to responseCode functionality:
https://github.com/viviotech/mod_cfml/issues/26

**Comment by utdream** [comment]
Okay, I think I understand now. The Apache 2.4/mod_proxy_ajp "secret" param won't be supported until Apache 2.4.42, which we're still waiting for a production release on. This check is just to check to see if the VC16 builds work. Got it. All caught up now.

**Comment by utdream** [comment]
updates made. changes committed.

**Comment by paulklinkenberg** [comment]
@utdream I will update the version number, and do a rebuild.

**Comment by utdream** [comment]
@paulklinkenberg Thank you brother.
