### ISSUE TITLE
More redirect issues - index.cfm?&__&__&__&__&__&__&__

### ISSUE THREAD

**Issue by jpmyob** [viviotech/mod_cfml#28]
I am getting too many redirects after implementing a solution to THIS problem
"mod_jk to shows/append index.cfm?&_modcfmlredirected on page load"

I am trying to run Lucee CF with Apache 2.4 on a windows EC2 instance.

Install of both Apache 2.4 and Lucee went fine - both services come up fine and restart fine... Apache conf is pointed to a webroot - and test page comes up fine.

I have followed instructions on implementing mod_jk - but when I tested a simple index.cfm - I got this:

    index.cfm?&_modcfmlredirected

I found multiple answers - that all recommended updating your 'mod_cfml-valve_v1.1.09.jar' to 'mod_cfml-valve_v1.1.10.jar'. 

So I did...

And now I get this:

    http://127.0.0.1/index.cfm?&__&__&__&__&__&__&__&__&__&__&__&__&__&__&__&__&__&__&__

    This page isn’t working 127.0.0.1 redirected you too many times.
    Try clearing your cookies.
    ERR_TOO_MANY_REDIRECTS

reverting to the 1.1.09 file brings back the ?&_modcfmlredirected as expected.

The code of index.cfm is simply 

    CF Index : 
    <cfoutput>#now()#</cfoutput>

This is not a 'code' issue....

Any help is greatly appreciated.

**Comment by jpmyob** [comment]
**** ADDITIONAL INFORMATION ****
this redirect happens when viewing file from localhost (127.0.0.1)
however, when I view the page from outside the server - I get a 403 - Forbidden error.

 don't know id this helps - I hope so.

**Comment by utdream** [comment]
Hi @jpmyob ,

Can you turn on logging for both the mod_cfml apache module and for the mod_cfml tomcat valve and send me the logs from when this happens? I need to fully understand what's happening on your system in order to diagnose and fix this for you.

Documentation on how to turn on logging for both the web server and the tomcat module is on the mod_cfml site:
http://viviotech.github.io/mod_cfml/

Thank you for taking the time to report this!

**Comment by jpmyob** [comment]
I'll be happy to - but I do not see - on your link page - where it tells me how to log for those two specific things?
would it just be in the errors log file? or access log?
JP 

    On Thursday, August 22, 2019, 03:35:46 PM CDT, Jordan Michaels <notifications@github.com> wrote:  
 
 
Hi @jpmyob ,

Can you turn on logging for both the mod_cfml apache module and for the mod_cfml tomcat valve and send me the logs from when this happens? I need to fully understand what's happening on your system in order to diagnose and fix this for you.

Documentation on how to turn on logging for both the web server and the tomcat module is on the mod_cfml site:
http://viviotech.github.io/mod_cfml/

Thank you for taking the time to report this!

**Comment by utdream** [comment]
Hi @jpmyob ,

The configuration options are mentioned on the pages for the specific modules that you're using. For example, on the Tomcat module:
http://viviotech.github.io/mod_cfml/docs-valve.html

The option is to set "loggingEnabled" to "true". I don't know what web server you're using, but if you're using Apache you would want to set all the log options to "true":
http://viviotech.github.io/mod_cfml/docs-modcfml.html

Looking forward to seeing what's going on here...

**Comment by jpmyob** [comment]
Thx jordan - I did as you directed - 
I cannot now, connect to the cf admin.
I will get it figured out and pass along the logs when i can
thx

JP 

    On Friday, August 23, 2019, 11:48:26 AM CDT, Jordan Michaels <notifications@github.com> wrote:  
 
 
Hi @jpmyob ,

The configuration options are mentioned on the pages for the specific modules that you're using. For example, on the Tomcat module:
http://viviotech.github.io/mod_cfml/docs-valve.html

The option is to set "loggingEnabled" to "true". I don't know what web server you're using, but if you're using Apache you would want to set all the log options to "true":
http://viviotech.github.io/mod_cfml/docs-modcfml.html

Looking forward to seeing what's going on here...

**Comment by jpmyob** [comment]
I agree - and will get it to you asap.
JP 

    On Monday, August 26, 2019, 11:14:10 AM CDT, Jordan Michaels <notifications@github.com> wrote:  
 
 
Hi @jpmyob ,

Turning on logging shouldn't have any affect on how the mappings function, it just logs it. There must be something more that is going on.... that's why we need the logging!

If I can help in any way, please let me know.

-Jordan

**Comment by jpmyob** [comment]
Thanks - I finally had some time to work on this 
and had to reinstall Lucee - this time w/o IIS connector...

When I swapped the valve 1.1.09 with 1.1.10 - Lucee wouldn't start...
I actually "renamed" the valve to 1.1.09 (even though it's the .10 jar...and Lucee started.
but I still got the "redirect' url variable - but I DID NOT get the multiple redirects or looping...
So - long story short - whatever I did on reinstall helped a lot.

Thx for pointing me in a direction, I have a knack for finding (falling victim) to obscure bugs...

JP 

    On Tuesday, August 27, 2019, 7:05:36 PM CDT, Jordan Michaels <notifications@github.com> wrote:  
 
 
I have been able to duplicate this in a lab environment, so I will get to work on a fix.

**Comment by utdream** [comment]
Good to know. I haven't had time (until just now) to look into this fully, but now that I have the issue duplicated in the lab I'll work out a patch here soon...

Thank you again for taking the time to report this. It is very appreciated!

**Comment by utdream** [comment]
Okay, so, I just had an experience that was quite similar to yours. In my case, new contexts were getting created without a URL value (what is essentially a null context), when I went to go restart, the restart was dirty and ended up being forced by the lucee_ctl script - every time. I dug into that a bit more and found that Lucee was crashing with a JVM crash dump - something about a timeout waiting on Felix. Tragically, I didn't keep the error. Instead I tried reinstalling and now everything works perfect and beautiful, and I cannot reproduce the error!

**Comment by utdream** [comment]
If you log in to the Lucee Server Admin area, click the "Overview" page and scroll to the bottom, you should see a list of the contexts that exist on your system. The URL values of those contexts should be something like "http://mysite.local:80", and so forth. That is a healthy context. However, the contexts that were being created for me had a null URL value, but proper webroot and config file values.

Mod_cfml already has safe-guards that protect it from creating contexts with null values or values that already exist, so my guess is that what is happening here is that mod_cfml is getting a proper context config from the apache module, passing the proper config to Tomcat, but because there is something wrong with the Tomcat/Java stack, those contexts aren't getting created properly.

We need to figure out what exactly is preventing these contexts from getting created properly, and then we can explore what we can do about it from a mod_cfml point of view. For example, perhaps we can listen for feedback from the host.addalias() method or perhaps there is something other than an exception that we need to catch from the engine.addchild() method.

I need more information here.

**Comment by jpmyob** [comment]
I'll see what I can turn up and document along the way

JP 

    On Wednesday, August 28, 2019, 8:33:03 PM CDT, Jordan Michaels <notifications@github.com> wrote:  
 
 
If you log in to the Lucee Server Admin area, click the "Overview" page and scroll to the bottom, you should see a list of the contexts that exist on your system. The URL values of those contexts should be something like "http://mysite.local:80", and so forth. That is a healthy context. However, the contexts that were being created for me had a null URL value, but proper webroot and config file values.

Mod_cfml already has safe-guards that protect it from creating contexts with null values or values that already exist, so my guess is that what is happening here is that mod_cfml is getting a proper context config from the apache module, passing the proper config to Tomcat, but because there is something wrong with the Tomcat/Java stack, those contexts aren't getting created properly.

We need to figure out what exactly is preventing these contexts from getting created properly, and then we can explore what we can do about it from a mod_cfml point of view. For example, perhaps we can listen for feedback from the host.addalias() method or perhaps there is something other than an exception that we need to catch from the engine.addchild() method.

I need more information here.

**Comment by ZAV79** [comment]
I saw something very similar to this, on windows, and for me it was because the service account I was running tomcat under didn't have permissions to change the directory Lucee was installed in

**Comment by utdream** [comment]
Going to change the status of this to "not a bug" due to it seeming to indicate an issue with the system that mod_cfml is installed on rather than an issue with mod_cfml itself.
